[package]
name = "honors"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
docx-rs = "0.2"
rand = "0.8"
aes-gcm = "0.9"
base64 = "0.13"
rsa = "0.5"
docx-rust = "0.1.5"